# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import datos_pb2 as datos__pb2


class ServicioDatosStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.obtenerDatos = channel.stream_stream(
                '/p2.ServicioDatos/obtenerDatos',
                request_serializer=datos__pb2.Datos.SerializeToString,
                response_deserializer=datos__pb2.Respuesta.FromString,
                )


class ServicioDatosServicer(object):
    """Missing associated documentation comment in .proto file"""

    def obtenerDatos(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicioDatosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'obtenerDatos': grpc.stream_stream_rpc_method_handler(
                    servicer.obtenerDatos,
                    request_deserializer=datos__pb2.Datos.FromString,
                    response_serializer=datos__pb2.Respuesta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2.ServicioDatos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServicioDatos(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def obtenerDatos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/p2.ServicioDatos/obtenerDatos',
            datos__pb2.Datos.SerializeToString,
            datos__pb2.Respuesta.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
