# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datos.proto',
  package='p2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x64\x61tos.proto\x12\x02p2\"c\n\x05\x44\x61tos\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65partamento\x18\x02 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x03 \x01(\t\x12\x16\n\x0e\x66orma_contagio\x18\x04 \x01(\t\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\")\n\tRespuesta\x12\x0f\n\x07\x45nviado\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2=\n\rServicioDatos\x12,\n\x0cobtenerDatos\x12\t.p2.Datos\x1a\r.p2.Respuesta(\x01\x30\x01\x62\x06proto3'
)




_DATOS = _descriptor.Descriptor(
  name='Datos',
  full_name='p2.Datos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='p2.Datos.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='departamento', full_name='p2.Datos.departamento', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edad', full_name='p2.Datos.edad', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forma_contagio', full_name='p2.Datos.forma_contagio', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estado', full_name='p2.Datos.estado', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=118,
)


_RESPUESTA = _descriptor.Descriptor(
  name='Respuesta',
  full_name='p2.Respuesta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Enviado', full_name='p2.Respuesta.Enviado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='p2.Respuesta.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['Datos'] = _DATOS
DESCRIPTOR.message_types_by_name['Respuesta'] = _RESPUESTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Datos = _reflection.GeneratedProtocolMessageType('Datos', (_message.Message,), {
  'DESCRIPTOR' : _DATOS,
  '__module__' : 'datos_pb2'
  # @@protoc_insertion_point(class_scope:p2.Datos)
  })
_sym_db.RegisterMessage(Datos)

Respuesta = _reflection.GeneratedProtocolMessageType('Respuesta', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTA,
  '__module__' : 'datos_pb2'
  # @@protoc_insertion_point(class_scope:p2.Respuesta)
  })
_sym_db.RegisterMessage(Respuesta)



_SERVICIODATOS = _descriptor.ServiceDescriptor(
  name='ServicioDatos',
  full_name='p2.ServicioDatos',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='obtenerDatos',
    full_name='p2.ServicioDatos.obtenerDatos',
    index=0,
    containing_service=None,
    input_type=_DATOS,
    output_type=_RESPUESTA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICIODATOS)

DESCRIPTOR.services_by_name['ServicioDatos'] = _SERVICIODATOS

# @@protoc_insertion_point(module_scope)
